### ISSUE TITLE
demo password changed?

### ISSUE THREAD

**Issue by alter72** [neo-classic/yiimine#2]
не пускает с admin / admin
кто то сменил? запретить! :)

**Comment by neo-classic** [comment]
привет
вот сучата))) ок, закрыл, вернул пароль назад
Спасибо :)

2016-01-18 12:22 GMT+03:00 Dmitriy Ikrin <notifications@github.com>:

> не пускает с admin / admin
> кто то сменил? запретить! :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/neo-classic/yiimine/issues/2>.
>



-- 
Есть такая профессия - код писать.

С уважением, Беляков Юрий.
*Skype*: a6curd
*Сайт*: http://belyakov.su
