### ISSUE TITLE
RBAC, view

### ISSUE THREAD

**Issue by gromdron** [neo-classic/yiimine#3]
Я чего-то не понимаю или у вас есть возможность просматривать проекты и таблицу issue, без авторизации:
http://yiimine.by-dev.com/issue/index?id=9

По данным ссылкам посмотрел проекты, и часть задач(без данных) + wiki и файлы.

**Comment by neo-classic** [comment]
Есть открытые проекты, есть закрытые. Можете зайти admin / admin, и всё поймете
